# Generated by Django 4.2.3 on 2024-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0002_student_alter_drumlesson_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drumlesson',
            name='name',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced')], max_length=50),
        ),
    ]
