# Generated by Django 4.2.3 on 2024-07-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0002_remove_drumlesson_option_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drumlesson_option',
            name='slot',
        ),
        migrations.AddField(
            model_name='drumlesson_option',
            name='slots',
            field=models.ManyToManyField(to='orak.slot'),
        ),
        migrations.AlterField(
            model_name='student',
            name='drumlesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orak.drumlesson_option', unique=True),
        ),
    ]
