# Generated by Django 4.2.3 on 2024-06-06 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0004_alter_drumlesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drumlesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orak.student'),
        ),
        migrations.AlterField(
            model_name='drumlesson',
            name='lesson_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lesson Date'),
            preserve_default=False,
        ),
    ]
