# Generated by Django 4.2.3 on 2024-06-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0005_drumlesson_student_alter_drumlesson_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drumlesson',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orak.drumlesson'),
        ),
    ]
