# Generated by Django 4.2.3 on 2024-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0006_remove_drumlesson_student_student_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='drumlesson',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
    ]
