# Generated by Django 4.2.3 on 2024-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0008_slot_remove_drumlesson_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drumlesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='drumlesson',
            name='slot',
        ),
        migrations.AddField(
            model_name='drumlesson',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Lesson Date'),
        ),
        migrations.AddField(
            model_name='drumlesson',
            name='lesson_date',
            field=models.DateTimeField(null=True, verbose_name='Lesson Date'),
        ),
        migrations.AddField(
            model_name='drumlesson',
            name='lesson_length',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drumlesson',
            name='lesson_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drumlesson',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='drumlesson',
            name='name',
            field=models.CharField(choices=[('Élő', 'Élő'), ('Offline', 'Offline')], max_length=50),
        ),
    ]
