# Generated by Django 4.2.3 on 2024-06-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orak', '0012_remove_slot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='drumlesson_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Élő dobóra', 'Élő dobóra'), ('Offline dobóra', 'Offline dobóra')], max_length=50)),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orak.slot')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.DeleteModel(
            name='drumlesson',
        ),
        migrations.AddField(
            model_name='student',
            name='drumlesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orak.drumlesson_option'),
        ),
    ]
